In [101]:
#William Dahl
#ICSI 426
#HW4
#March 4th 2019

import numpy
from numpy import linalg

#data matrix X
X = numpy.matrix([[-2,1,4,6,5,3,6,2],
                 [9,3,2,-1,-4,-2,-4,5],
                 [0,7,-5,3,2,-3,4,6]])

#mean of the values in each row
def func_mean(X):
    return X.mean(axis=1) #a 3x1 vector
 
#centers the matrix around the mean
def center(X,m):
    return X-m #the centeres matrix

#calculates the covatince matrix
def cov(X1):
    return X1 * X1.getT()
    
m = func_mean(X)
print('mean vector:')
print(m, '\n')

X1 = center(X,m)
print('Centered data matrix:')
print(X1, '\n')

C = cov(X1)
print('Covarinace matrix:')
print(C, '\n')

val, vec = linalg.eig(C)
print('First PC:')
sorted_index = val.argsort()[::-1] 
val = val[sorted_index]
vec = vec[:,sorted_index]
print(vec[0], '\n')

#cakculates the 1D representation 
def one_D_reduction(X, vec):
    return (X.getT() * vec.getT()).T

print('1D representaion of X:')
print(one_D_reduction(X, vec[0]), '\n')

#Performs principla compnoet anaylsis to a specifed degree k
def mypca(X,k):
    m = func_mean(X) #gets mean vector
    X1 = center(X,m) #Center X
    C = cov(X1) #gets the covarince matrix of X
    val, vec = linalg.eig(C) #gets the eigen values and the eiginvectors
    sorted_index = val.argsort()[::-1] #gets the sorted index of the eigen values
    val = val[sorted_index]#sorts the eigen values
    vec = vec[:,sorted_index]#sorst the eigin vectots to go with their respective eigin values
    pc = vec[:,:k]#gets the first k eigen vectors
    pv = val[:k] #gets the first k egin values
    rep = X.getT() * pc #calculates the k diminsial represenative for matrix X
    return rep.T, pc, pv

#calculates the best 2D representation for data matrix X
rep, pc, pv = mypca(X,2)
print('rep of 2 dimensions:')
print(rep, '\n')
print('PC:')
print(pc, '\n')
print("PV:")
print(pv, '\n')

mean vector:
[[3.125]
 [1.   ]
 [1.75 ]] 

Centered data matrix:
[[-5.125 -2.125  0.875  2.875  1.875 -0.125  2.875 -1.125]
 [ 8.     2.     1.    -2.    -5.    -3.    -5.     4.   ]
 [-1.75   5.25  -6.75   1.25   0.25  -4.75   2.25   4.25 ]] 

Covarinace matrix:
[[ 52.875 -78.     -1.75 ]
 [-78.    148.      6.   ]
 [ -1.75    6.    123.5  ]] 

First PC:
[[-0.48708504  0.05390734 -0.87168926]] 

1D representaion of X:
[[ 1.45933613 -6.42718784  2.51792084 -5.59148533 -4.39443306  1.045998
  -6.62489661 -5.93476893]] 

rep of 2 dimensions:
[[ 8.79424627  2.73646372 -0.65115735 -3.52704041 -5.73476983 -3.46341697
  -6.04561009  3.89905101]
 [-0.74498789  6.81374742 -4.9061298   3.38234013  2.54479084 -2.684783
   4.59076422  5.73002769]] 

PC:
[[-0.48708504  0.05390734]
 [ 0.86889736 -0.07079702]
 [ 0.08812238  0.99603302]] 

PV:
[192.33362217 122.97881247] 

